### ISSUE TITLE
Integrating Flutter app with Flask API

### ISSUE THREAD

**Issue by grace-sodunke** [grace-sodunke/MoodSmart#2]
Hi, I'm trying to send a POST request from the Flutter app to the Flask API and would like guidance as to how to complete this. I haven't been able to successfully create a virtual environment that runs this Flask framework on my local device since installing all dependencies raises errors (and I have tried to recreate the virtual environment more than once without success).
 
In Flutter, I have used this code to make a POST request:
` _makePostRequest() async {`
`    // set up POST request arguments`
`    String url = 'http://127.0.0.1:5000/predict';`
`    Map<String, String> headers = {"Content-type": "application/json"};`
`    String json =`
`        '{"tweet": "Feeling really stressed out about the work piling up at the moment... :("}';`
`    // make POST request`
`    Response response = await post(url, headers: headers, body: json);`
`    // check the status code for the result`
`    int statusCode = response.statusCode;`
`    // this API passes back the id of the new item added to the body`
`    String body = response.body;`
`    return body;`
`  }`

I think that the main issue is connecting the application to the localhost, which hasn't worked in both the backend and frontend.

**Comment by grace-sodunke** [comment]
This is the error I get when trying to run the framework in the environment:

(teensinai) C:\Users\User\PycharmProjects\MoodSmart\MoodSmart-master\backend>flask run --without-threads
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Using TensorFlow backend.
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\user\miniconda3\envs\teensinai\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\user\miniconda3\envs\teensinai\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\User\PycharmProjects\MoodSmart\MoodSmart-master\backend\app.py", line 9, in <module>
    from keras.preprocessing.text import tokenizer_from_json
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\user\miniconda3\envs\teensinai\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\user\miniconda3\envs\teensinai\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\user\miniconda3\envs\teensinai\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

**Comment by grace-sodunke** [comment]
UPDATE: I have been able to get the Flask framework to run on my machine by downgrading to Tensorflow 2.0.0.

**Comment by jamessandy** [comment]
so now the Flask API  works fine ?

**Comment by grace-sodunke** [comment]
It's looks like it is working right now, I'll let you know when we require further assistance. Thank you!

**Comment by jamessandy** [comment]
Nice, i'll be here. Please close the issue
